# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Run tests with Maven
      run: mvn -B test --file pom.xml
        
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: 🛠 Coveralls Coverage Report Setup
      run: sed -i.bak 's/yourcoverallsprojectrepositorytoken/${{ secrets.COVERALL_REPO_SECRET }}/g' pom.xml
    - name: 🚀 Coveralls Coverage Report Submission
      run: mvn coveralls:report
    
    - name: 🧹 Cleanup Repository Token
      if: ${{ always() }}
      run: if [ -f "pom.xml.bak" ]; then mv pom.xml.bak pom.xml; fi
      
  release:
    runs-on: ubuntu-latest
    name: release
    steps:
    - uses: radcortez/project-metadata-action@master
      name: Retrieve project metadata
      id: metadata
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        metadata-file-path: '.github/project.yml'
  
    - uses: actions/checkout@v2

    - name: Import GPG key
      id: import_gpg
      uses: crazy-max/ghaction-import-gpg@v3
      with:
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_PASSPHRASE }}

    - name: Install JDK 11
      uses: joschi/setup-jdk@e87a7cec853d2dd7066adf837fe12bf0f3d45e52
      with:
        distribution: 'temurin'
        java-version: 11
        check-latest: true

    - name: Configure Git author
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    - name: Maven release $
      run: |
        gpg --quiet --batch --yes --decrypt --passphrase=${{ secrets.GPG_PASSPHRASE }} --output maven-settings.xml .github/release/maven-settings.xml.gpg
        git checkout -b release
        mvn -X -Prelease -B release:clean release:prepare -DreleaseVersion=${{steps.metadata.outputs.current-version}} -DdevelopmentVersion=${{steps.metadata.outputs.NEXT-version}} -s maven-settings.xml
        git checkout 
        git rebase release
        mvn -X -Prelease -B release:perform -DskipTests -s maven-settings.xml
    - name: Push changes to $
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        branch: master

    - name: Push tags
      uses: ad-m/github-push-action@v0.6.0
      with:
        branch: master
        github_token: ${{secrets.GITHUB_TOKEN}}
        tags: true
